version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: